<?php

use Illuminate\Database\Seeder;

class ParishesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('parishes')->insert([
            ['parish' => 'Alto Orinoco', 'municipality_id' => 1],
            ['parish' => 'Huachamacare Acanaña', 'municipality_id' => 1],
            ['parish' => 'Marawaka Toky Shamanaña', 'municipality_id' => 1],
            ['parish' => 'Mavaka Mavaka', 'municipality_id' => 1],
            ['parish' => 'Sierra Parima Parimabé', 'municipality_id' => 1],
            ['parish' => 'Ucata Laja Lisa', 'municipality_id' => 2],
            ['parish' => 'Yapacana Macuruco', 'municipality_id' => 2],
            ['parish' => 'Caname Guarinuma', 'municipality_id' => 2],
            ['parish' => 'Fernando Girón Tovar', 'municipality_id' => 3],
            ['parish' => 'Luis Alberto Gómez', 'municipality_id' => 3],
            ['parish' => 'Pahueña Limón de Parhueña', 'municipality_id' => 3],
            ['parish' => 'Platanillal Platanillal', 'municipality_id' => 3],
            ['parish' => 'Samariapo', 'municipality_id' => 4],
            ['parish' => 'Sipapo', 'municipality_id' => 4],
            ['parish' => 'Munduapo', 'municipality_id' => 4],
            ['parish' => 'Guayapo', 'municipality_id' => 4],
            ['parish' => 'Alto Ventuari', 'municipality_id' => 5],
            ['parish' => 'Medio Ventuari', 'municipality_id' => 5],
            ['parish' => 'Bajo Ventuari', 'municipality_id' => 5],
            ['parish' => 'Victorino', 'municipality_id' => 6],
            ['parish' => 'Comunidad', 'municipality_id' => 6],
            ['parish' => 'Casiquiare', 'municipality_id' => 7],
            ['parish' => 'Cocuy', 'municipality_id' => 7],
            ['parish' => 'San Carlos de Río Negro', 'municipality_id' => 7],
            ['parish' => 'Solano', 'municipality_id' => 7],
            ['parish' => 'Anaco', 'municipality_id' => 8],
            ['parish' => 'San Joaquín', 'municipality_id' => 8],
            ['parish' => 'Cachipo', 'municipality_id' => 9],
            ['parish' => 'Aragua de Barcelona', 'municipality_id' => 9],
            ['parish' => 'Lechería', 'municipality_id' => 11],
            ['parish' => 'El Morro', 'municipality_id' => 11],
            ['parish' => 'Puerto Píritu', 'municipality_id' => 12],
            ['parish' => 'San Miguel', 'municipality_id' => 12],
            ['parish' => 'Sucre', 'municipality_id' => 12],
            ['parish' => 'Valle de Guanape', 'municipality_id' => 13],
            ['parish' => 'Santa Bárbara', 'municipality_id' => 13],
            ['parish' => 'El Chaparro', 'municipality_id' => 14],
            ['parish' => 'Tomás Alfaro', 'municipality_id' => 14],
            ['parish' => 'Calatrava', 'municipality_id' => 14],
            ['parish' => 'Guanta', 'municipality_id' => 15],
            ['parish' => 'Chorrerón', 'municipality_id' => 15],
            ['parish' => 'Mamo', 'municipality_id' => 16],
            ['parish' => 'Soledad', 'municipality_id' => 16],
            ['parish' => 'Mapire', 'municipality_id' => 17],
            ['parish' => 'Piar', 'municipality_id' => 17],
            ['parish' => 'Santa Clara', 'municipality_id' => 17],
            ['parish' => 'San Diego de Cabrutica', 'municipality_id' => 17],
            ['parish' => 'Uverito', 'municipality_id' => 17],
            ['parish' => 'Zuata', 'municipality_id' => 17],
            ['parish' => 'Puerto La Cruz', 'municipality_id' => 18],
            ['parish' => 'Pozuelos', 'municipality_id' => 18],
            ['parish' => 'Onoto', 'municipality_id' => 19],
            ['parish' => 'San Pablo', 'municipality_id' => 19],
            ['parish' => 'San Mateo', 'municipality_id' => 20],
            ['parish' => 'El Carito', 'municipality_id' => 20],
            ['parish' => 'Santa Inés', 'municipality_id' => 20],
            ['parish' => 'La Romereña', 'municipality_id' => 20],
            ['parish' => 'Atapirire', 'municipality_id' => 21],
            ['parish' => 'Boca del Pao', 'municipality_id' => 21],
            ['parish' => 'El Pao', 'municipality_id' => 21],
            ['parish' => 'Pariaguán', 'municipality_id' => 21],
            ['parish' => 'Cantaura', 'municipality_id' => 22],
            ['parish' => 'Libertador', 'municipality_id' => 22],
            ['parish' => 'Santa Rosa', 'municipality_id' => 22],
            ['parish' => 'Urica', 'municipality_id' => 22],
            ['parish' => 'Píritu', 'municipality_id' => 23],
            ['parish' => 'San Francisco', 'municipality_id' => 23],
            ['parish' => 'San José de Guanipa', 'municipality_id' => 24],
            ['parish' => 'Boca de Uchire', 'municipality_id' => 25],
            ['parish' => 'Boca de Chávez', 'municipality_id' => 25],
            ['parish' => 'Pueblo Nuevo', 'municipality_id' => 26],
            ['parish' => 'Santa Ana', 'municipality_id' => 26],
            ['parish' => 'Bergantín', 'municipality_id' => 27],
            ['parish' => 'Caigua', 'municipality_id' => 27],
            ['parish' => 'El Carmen', 'municipality_id' => 27],
            ['parish' => 'El Pilar', 'municipality_id' => 27],
            ['parish' => 'Naricual', 'municipality_id' => 27],
            ['parish' => 'San Crsitóbal', 'municipality_id' => 27],
            ['parish' => 'Edmundo Barrios', 'municipality_id' => 28],
            ['parish' => 'Miguel Otero Silva', 'municipality_id' => 28],
            ['parish' => 'Achaguas', 'municipality_id' => 29],
            ['parish' => 'Apurito', 'municipality_id' => 29],
            ['parish' => 'El Yagual', 'municipality_id' => 29],
            ['parish' => 'Guachara', 'municipality_id' => 29],
            ['parish' => 'Mucuritas', 'municipality_id' => 29],
            ['parish' => 'Queseras del medio', 'municipality_id' => 29],
            ['parish' => 'Biruaca', 'municipality_id' => 30],
            ['parish' => 'Bruzual', 'municipality_id' => 31],
            ['parish' => 'Mantecal', 'municipality_id' => 31],
            ['parish' => 'Quintero', 'municipality_id' => 31],
            ['parish' => 'Rincón Hondo', 'municipality_id' => 31],
            ['parish' => 'San Vicente', 'municipality_id' => 31],
            ['parish' => 'Guasdualito', 'municipality_id' => 32],
            ['parish' => 'Aramendi', 'municipality_id' => 32],
            ['parish' => 'El Amparo', 'municipality_id' => 32],
            ['parish' => 'San Camilo', 'municipality_id' => 32],
            ['parish' => 'Urdaneta', 'municipality_id' => 32],
            ['parish' => 'San Juan de Payara', 'municipality_id' => 33],
            ['parish' => 'Codazzi', 'municipality_id' => 33],
            ['parish' => 'Cunaviche', 'municipality_id' => 33],
            ['parish' => 'Elorza', 'municipality_id' => 34],
            ['parish' => 'La Trinidad', 'municipality_id' => 34],
            ['parish' => 'San Fernando', 'municipality_id' => 35],
            ['parish' => 'El Recreo', 'municipality_id' => 35],
            ['parish' => 'Peñalver', 'municipality_id' => 35],
            ['parish' => 'San Rafael de Atamaica', 'municipality_id' => 35],
            ['parish' => 'Pedro José Ovalles', 'municipality_id' => 36],
            ['parish' => 'Joaquín Crespo', 'municipality_id' => 36],
            ['parish' => 'José Casanova Godoy', 'municipality_id' => 36],
            ['parish' => 'Madre María de San José', 'municipality_id' => 36],
            ['parish' => 'Andrés Eloy Blanco', 'municipality_id' => 36],
            ['parish' => 'Los Tacarigua', 'municipality_id' => 36],
            ['parish' => 'Las Delicias', 'municipality_id' => 36],
            ['parish' => 'Choroní', 'municipality_id' => 36],
            ['parish' => 'Bolívar', 'municipality_id' => 37],
            ['parish' => 'Camatagua', 'municipality_id' => 38],
            ['parish' => 'Carmen de Cura', 'municipality_id' => 38],
            ['parish' => 'Santa Rita', 'municipality_id' => 39],
            ['parish' => 'Francisco de Miranda', 'municipality_id' => 39],
            ['parish' => 'Moseñor Feliciano González', 'municipality_id' => 39],
            ['parish' => 'Santa Cruz', 'municipality_id' => 40],
            ['parish' => 'José Félix Ribas', 'municipality_id' => 41],
            ['parish' => 'Castor Nieves Ríos', 'municipality_id' => 41],
            ['parish' => 'Las Guacamayas', 'municipality_id' => 41],
            ['parish' => 'Pao de Zárate', 'municipality_id' => 41],
            ['parish' => 'Zuata', 'municipality_id' => 41],
            ['parish' => 'José Rafael Revenga', 'municipality_id' => 42],
            ['parish' => 'Palo Negro', 'municipality_id' => 43],
            ['parish' => 'San Martín de Porres', 'municipality_id' => 43],
            ['parish' => 'El Limón', 'municipality_id' => 44],
            ['parish' => 'Caña de Azúcar', 'municipality_id' => 44],
            ['parish' => 'Ocumare de la Costa', 'municipality_id' => 45],
            ['parish' => 'San Casimiro', 'municipality_id' => 46],
            ['parish' => 'Güiripa', 'municipality_id' => 46],
            ['parish' => 'Ollas de Caramacate', 'municipality_id' => 46],
            ['parish' => 'Valle Morín', 'municipality_id' => 46],
            ['parish' => 'San Sebastían', 'municipality_id' => 47],
            ['parish' => 'Turmero', 'municipality_id' => 48],
            ['parish' => 'Arevalo Aponte', 'municipality_id' => 48],
            ['parish' => 'Chuao', 'municipality_id' => 48],
            ['parish' => 'Samán de Güere', 'municipality_id' => 48],
            ['parish' => 'Alfredo Pacheco Miranda', 'municipality_id' => 48],
            ['parish' => 'Santos Michelena', 'municipality_id' => 49],
            ['parish' => 'Tiara', 'municipality_id' => 49],
            ['parish' => 'Cagua', 'municipality_id' => 50],
            ['parish' => 'Bella Vista', 'municipality_id' => 50],
            ['parish' => 'Tovar', 'municipality_id' => 51],
            ['parish' => 'Urdaneta', 'municipality_id' => 52],
            ['parish' => 'Las Peñitas', 'municipality_id' => 52],
            ['parish' => 'San Francisco de Cara', 'municipality_id' => 52],
            ['parish' => 'Taguay', 'municipality_id' => 52],
            ['parish' => 'Zamora', 'municipality_id' => 53],
            ['parish' => 'Magdaleno', 'municipality_id' => 53],
            ['parish' => 'San Francisco de Asís', 'municipality_id' => 53],
            ['parish' => 'Valles de Tucutunemo', 'municipality_id' => 53],
            ['parish' => 'Augusto Mijares', 'municipality_id' => 53],
            ['parish' => 'Sabaneta', 'municipality_id' => 54],
            ['parish' => 'Juan Antonio Rodríguez Domínguez', 'municipality_id' => 54],
            ['parish' => 'El Cantón', 'municipality_id' => 55],
            ['parish' => 'Santa Cruz de Guacas', 'municipality_id' => 55],
            ['parish' => 'Puerto Vivas', 'municipality_id' => 55],
            ['parish' => 'Ticoporo', 'municipality_id' => 56],
            ['parish' => 'Nicolás Pulido', 'municipality_id' => 56],
            ['parish' => 'Andrés Bello', 'municipality_id' => 56],
            ['parish' => 'Arismendi', 'municipality_id' => 57],
            ['parish' => 'Guadarrama', 'municipality_id' => 57],
            ['parish' => 'La Unión', 'municipality_id' => 57],
            ['parish' => 'San Antonio', 'municipality_id' => 57],
            ['parish' => 'Barinas', 'municipality_id' => 58],
            ['parish' => 'Alberto Arvelo Larriva', 'municipality_id' => 58],
            ['parish' => 'San Silvestre', 'municipality_id' => 58],
            ['parish' => 'Santa Inés', 'municipality_id' => 58],
            ['parish' => 'Santa Lucía', 'municipality_id' => 58],
            ['parish' => 'Torumos', 'municipality_id' => 58],
            ['parish' => 'El Carmen', 'municipality_id' => 58],
            ['parish' => 'Rómulo Betancourt', 'municipality_id' => 58],
            ['parish' => 'Corazón de Jesús', 'municipality_id' => 58],
            ['parish' => 'Ramón Ignacio Méndez', 'municipality_id' => 58],
            ['parish' => 'Alto Barinas', 'municipality_id' => 58],
            ['parish' => 'Manuel Palacio Fajardo', 'municipality_id' => 58],
            ['parish' => 'Juan Antonio Rodríguez Domínguez', 'municipality_id' => 58],
            ['parish' => 'Dominga Ortiz de Páez', 'municipality_id' => 58],
            ['parish' => 'Barinitas', 'municipality_id' => 59],
            ['parish' => 'Altamira de Cáceres', 'municipality_id' => 59],
            ['parish' => 'Calderas', 'municipality_id' => 59],
            ['parish' => 'Barrancas', 'municipality_id' => 60],
            ['parish' => 'El Socorro', 'municipality_id' => 60],
            ['parish' => 'Mazparrito', 'municipality_id' => 60],
            ['parish' => 'Santa Bárbara', 'municipality_id' => 61],
            ['parish' => 'Pedro Briceño Méndez', 'municipality_id' => 61],
            ['parish' => 'Ramón Ignacio Méndez', 'municipality_id' => 61],
            ['parish' => 'José Ignacio del Pumar', 'municipality_id' => 61],
            ['parish' => 'Obispos', 'municipality_id' => 62],
            ['parish' => 'Guasimitos', 'municipality_id' => 62],
            ['parish' => 'El Real', 'municipality_id' => 62],
            ['parish' => 'La Luz', 'municipality_id' => 62],
            ['parish' => 'Ciudad Bolívia', 'municipality_id' => 63],
            ['parish' => 'José Ignacio Briceño', 'municipality_id' => 63],
            ['parish' => 'José Félix Ribas', 'municipality_id' => 63],
            ['parish' => 'Páez', 'municipality_id' => 63],
            ['parish' => 'Libertad', 'municipality_id' => 64],
            ['parish' => 'Dolores', 'municipality_id' => 64],
            ['parish' => 'Santa Rosa', 'municipality_id' => 64],
            ['parish' => 'Palacio Fajardo', 'municipality_id' => 64],
            ['parish' => 'Ciudad de Nutrias', 'municipality_id' => 65],
            ['parish' => 'El Regalo', 'municipality_id' => 65],
            ['parish' => 'Puerto Nutrias', 'municipality_id' => 65],
            ['parish' => 'Santa Catalina', 'municipality_id' => 65],
            ['parish' => 'Cachamay', 'municipality_id' => 66],
            ['parish' => 'Chirica', 'municipality_id' => 66],
            ['parish' => 'Dalla Costa', 'municipality_id' => 66],
            ['parish' => 'Once de Abril', 'municipality_id' => 66],
            ['parish' => 'Simón Bolívar', 'municipality_id' => 66],
            ['parish' => 'Unare', 'municipality_id' => 66],
            ['parish' => 'Universidad', 'municipality_id' => 66],
            ['parish' => 'Vista al Sol', 'municipality_id' => 66],
            ['parish' => 'Pozo Verde', 'municipality_id' => 66],
            ['parish' => 'Yocoima', 'municipality_id' => 66],
            ['parish' => '5 de Julio', 'municipality_id' => 66],
            ['parish' => 'Cedeño', 'municipality_id' => 67],
            ['parish' => 'Altagracia', 'municipality_id' => 67],
            ['parish' => 'Ascensión Farreras', 'municipality_id' => 67],
            ['parish' => 'Guaniamo', 'municipality_id' => 67],
            ['parish' => 'La Urbana', 'municipality_id' => 67],
            ['parish' => 'Pijiguaos', 'municipality_id' => 67],
            ['parish' => 'El Callao', 'municipality_id' => 68],
            ['parish' => 'Gran Sabana', 'municipality_id' => 69],
            ['parish' => 'Ikabarú', 'municipality_id' => 69],
            ['parish' => 'Catedral', 'municipality_id' => 70],
            ['parish' => 'Zea', 'municipality_id' => 70],
            ['parish' => 'Orinoco', 'municipality_id' => 70],
            ['parish' => 'José Antonio Páez', 'municipality_id' => 70],
            ['parish' => 'Marhuanta', 'municipality_id' => 70],
            ['parish' => 'Agua Salada', 'municipality_id' => 70],
            ['parish' => 'Vista Hermosa', 'municipality_id' => 70],
            ['parish' => 'La Sabanita', 'municipality_id' => 70],
            ['parish' => 'Panapana', 'municipality_id' => 70],
            ['parish' => 'Andrés Eloy Blanco', 'municipality_id' => 71],
            ['parish' => 'Pedro Cova', 'municipality_id' => 71],
            ['parish' => 'Raúl Leoni', 'municipality_id' => 72],
            ['parish' => 'Barceloneta', 'municipality_id' => 72],
            ['parish' => 'Santa Bárbara', 'municipality_id' => 72],
            ['parish' => 'San Francisco', 'municipality_id' => 72],
            ['parish' => 'Roscio', 'municipality_id' => 73],
            ['parish' => 'Salóm', 'municipality_id' => 73],
            ['parish' => 'Sifontes', 'municipality_id' => 74],
            ['parish' => 'Dalla Costa', 'municipality_id' => 74],
            ['parish' => 'San Isidro', 'municipality_id' => 74],
            ['parish' => 'Sucre', 'municipality_id' => 75],
            ['parish' => 'Aripao', 'municipality_id' => 75],
            ['parish' => 'Guarataro', 'municipality_id' => 75],
            ['parish' => 'Las Majadas', 'municipality_id' => 75],
            ['parish' => 'Moitaco', 'municipality_id' => 75],
            ['parish' => 'Padre Pedro Chien', 'municipality_id' => 76],
            ['parish' => 'Río Grande', 'municipality_id' => 76],
            ['parish' => 'Bejuma', 'municipality_id' => 77],
            ['parish' => 'Canoabo', 'municipality_id' => 77],
            ['parish' => 'Simón Bolívar', 'municipality_id' => 77],
            ['parish' => 'Güigüe', 'municipality_id' => 78],
            ['parish' => 'Carabobo', 'municipality_id' => 78],
            ['parish' => 'Tacarigua', 'municipality_id' => 78],
            ['parish' => 'Mariara', 'municipality_id' => 79],
            ['parish' => 'Aguas Calientes', 'municipality_id' => 79],
            ['parish' => 'Ciudad Alianza', 'municipality_id' => 80],
            ['parish' => 'Guacara', 'municipality_id' => 80],
            ['parish' => 'Yagua', 'municipality_id' => 80],
            ['parish' => 'Morón', 'municipality_id' => 81],
            ['parish' => 'Yagua', 'municipality_id' => 81],
            ['parish' => 'Tocuyito', 'municipality_id' => 82],
            ['parish' => 'Independencia', 'municipality_id' => 82],
            ['parish' => 'Los Guayos', 'municipality_id' => 83],
            ['parish' => 'Miranda', 'municipality_id' => 84],
            ['parish' => 'Montalbán', 'municipality_id' => 85],
            ['parish' => 'Naguanagua', 'municipality_id' => 86],
            ['parish' => 'Bartolomé Salóm', 'municipality_id' => 87],
            ['parish' => 'Democracia', 'municipality_id' => 87],
            ['parish' => 'Fraternidad', 'municipality_id' => 87],
            ['parish' => 'Goaigoaza', 'municipality_id' => 87],
            ['parish' => 'Juan José Flores', 'municipality_id' => 87],
            ['parish' => 'Unión', 'municipality_id' => 87],
            ['parish' => 'Borburata', 'municipality_id' => 87],
            ['parish' => 'Patanemo', 'municipality_id' => 87],
            ['parish' => 'San Diego', 'municipality_id' => 88],
            ['parish' => 'San Joaquín', 'municipality_id' => 89],
            ['parish' => 'Candelaria', 'municipality_id' => 90],
            ['parish' => 'Catedral', 'municipality_id' => 90],
            ['parish' => 'El Socorro', 'municipality_id' => 90],
            ['parish' => 'Miguel Peña', 'municipality_id' => 90],
            ['parish' => 'Rafael Urdaneta', 'municipality_id' => 90],
            ['parish' => 'San Blas', 'municipality_id' => 90],
            ['parish' => 'San José', 'municipality_id' => 90],
            ['parish' => 'Santa Rosa', 'municipality_id' => 90],
            ['parish' => 'Negro Primero', 'municipality_id' => 90],
            ['parish' => 'Cojedes', 'municipality_id' => 91],
            ['parish' => 'Juan de Mata Suárez', 'municipality_id' => 91],
            ['parish' => 'Tinaquillo', 'municipality_id' => 92],
            ['parish' => 'El Baúl', 'municipality_id' => 93],
            ['parish' => 'Sucre', 'municipality_id' => 93],
            ['parish' => 'La Aguadita', 'municipality_id' => 94],
            ['parish' => 'Macapo', 'municipality_id' => 94],
            ['parish' => 'El Pao', 'municipality_id' => 95],
            ['parish' => 'El Amparo', 'municipality_id' => 96],
            ['parish' => 'Libertad de Cojedes', 'municipality_id' => 96],
            ['parish' => 'Rómulo Gallegos', 'municipality_id' => 97],
            ['parish' => 'San Carlos de Austria', 'municipality_id' => 98],
            ['parish' => 'Juan Ángel Bravo', 'municipality_id' => 98],
            ['parish' => 'Manuel Manrique', 'municipality_id' => 98],
            ['parish' => 'General en Jefe José Laurencio Silva', 'municipality_id' => 99],
            ['parish' => 'Curiapo', 'municipality_id' => 100],
            ['parish' => 'Almirante Luis Brión', 'municipality_id' => 100],
            ['parish' => 'Francisco Aniceto Lugo', 'municipality_id' => 100],
            ['parish' => 'Manuel Renaud', 'municipality_id' => 100],
            ['parish' => 'Padre Barral', 'municipality_id' => 100],
            ['parish' => 'Santos de Abelgas', 'municipality_id' => 100],
            ['parish' => 'Imataca', 'municipality_id' => 101],
            ['parish' => 'Cinco de Julio', 'municipality_id' => 101],
            ['parish' => 'Juan Bautista Arismendi', 'municipality_id' => 101],
            ['parish' => 'Manuel Piar', 'municipality_id' => 101],
            ['parish' => 'Rómulo Gallegos', 'municipality_id' => 101],
            ['parish' => 'Pedernales', 'municipality_id' => 102],
            ['parish' => 'Luis Beltrán Prieto Figueroa', 'municipality_id' => 102],
            ['parish' => 'San José  Amacuro)', 'municipality_id' => 103],
            ['parish' => 'José Vidal Marcano', 'municipality_id' => 103],
            ['parish' => 'Juan Millán', 'municipality_id' => 103],
            ['parish' => 'Leonardo Ruíz Pineda', 'municipality_id' => 103],
            ['parish' => 'Mariscal Antonio José de Sucre', 'municipality_id' => 103],
            ['parish' => 'Monseñor Argimiro García', 'municipality_id' => 103],
            ['parish' => 'San Rafael  Amacuro)', 'municipality_id' => 103],
            ['parish' => 'Virgen del Valle', 'municipality_id' => 103],
            ['parish' => 'Clarines', 'municipality_id' => 104],
            ['parish' => 'Guanape', 'municipality_id' => 104],
            ['parish' => 'Sabana de Uchire', 'municipality_id' => 104],
            ['parish' => 'Capadare', 'municipality_id' => 104],
            ['parish' => 'La Pastora', 'municipality_id' => 104],
            ['parish' => 'Libertador', 'municipality_id' => 104],
            ['parish' => 'San Juan de los Cayos', 'municipality_id' => 104],
            ['parish' => 'Aracua', 'municipality_id' => 105],
            ['parish' => 'La Peña', 'municipality_id' => 105],
            ['parish' => 'San Luis', 'municipality_id' => 105],
            ['parish' => 'Bariro', 'municipality_id' => 106],
            ['parish' => 'Borojó', 'municipality_id' => 106],
            ['parish' => 'Capatárida', 'municipality_id' => 106],
            ['parish' => 'Guajiro', 'municipality_id' => 106],
            ['parish' => 'Seque', 'municipality_id' => 106],
            ['parish' => 'Zazárida', 'municipality_id' => 106],
            ['parish' => 'Valle de Eroa', 'municipality_id' => 106],
            ['parish' => 'Cacique Manaure', 'municipality_id' => 107],
            ['parish' => 'Norte', 'municipality_id' => 108],
            ['parish' => 'Carirubana', 'municipality_id' => 108],
            ['parish' => 'Santa Ana', 'municipality_id' => 108],
            ['parish' => 'Urbana Punta Cardón', 'municipality_id' => 108],
            ['parish' => 'La Vela de Coro', 'municipality_id' => 109],
            ['parish' => 'Acurigua', 'municipality_id' => 109],
            ['parish' => 'Guaibacoa', 'municipality_id' => 109],
            ['parish' => 'Las Calderas', 'municipality_id' => 109],
            ['parish' => 'Macoruca', 'municipality_id' => 109],
            ['parish' => 'Dabajuro', 'municipality_id' => 110],
            ['parish' => 'Agua Clara', 'municipality_id' => 111],
            ['parish' => 'Avaria', 'municipality_id' => 111],
            ['parish' => 'Pedregal', 'municipality_id' => 111],
            ['parish' => 'Piedra Grande', 'municipality_id' => 111],
            ['parish' => 'Purureche', 'municipality_id' => 111],
            ['parish' => 'Adaure', 'municipality_id' => 112],
            ['parish' => 'Adícora', 'municipality_id' => 112],
            ['parish' => 'Baraived', 'municipality_id' => 112],
            ['parish' => 'Buena Vista', 'municipality_id' => 112],
            ['parish' => 'Jadacaquiva', 'municipality_id' => 112],
            ['parish' => 'El Vínculo', 'municipality_id' => 112],
            ['parish' => 'El Hato', 'municipality_id' => 112],
            ['parish' => 'Moruy', 'municipality_id' => 112],
            ['parish' => 'Pueblo Nuevo', 'municipality_id' => 112],
            ['parish' => 'Agua Larga', 'municipality_id' => 113],
            ['parish' => 'El Paují', 'municipality_id' => 113],
            ['parish' => 'Independencia', 'municipality_id' => 113],
            ['parish' => 'Mapararí', 'municipality_id' => 113],
            ['parish' => 'Agua Linda', 'municipality_id' => 114],
            ['parish' => 'Araurima', 'municipality_id' => 114],
            ['parish' => 'Jacura', 'municipality_id' => 114],
            ['parish' => 'Tucacas', 'municipality_id' => 115],
            ['parish' => 'Boca de Aroa', 'municipality_id' => 115],
            ['parish' => 'Los Taques', 'municipality_id' => 116],
            ['parish' => 'Judibana', 'municipality_id' => 116],
            ['parish' => 'Mene de Mauroa', 'municipality_id' => 117],
            ['parish' => 'San Félix', 'municipality_id' => 117],
            ['parish' => 'Casigua', 'municipality_id' => 117],
            ['parish' => 'Guzmán Guillermo', 'municipality_id' => 118],
            ['parish' => 'Mitare', 'municipality_id' => 118],
            ['parish' => 'Río Seco', 'municipality_id' => 118],
            ['parish' => 'Sabaneta', 'municipality_id' => 118],
            ['parish' => 'San Antonio', 'municipality_id' => 118],
            ['parish' => 'San Gabriel', 'municipality_id' => 118],
            ['parish' => 'Santa Ana', 'municipality_id' => 118],
            ['parish' => 'Boca del Tocuyo', 'municipality_id' => 119],
            ['parish' => 'Chichiriviche', 'municipality_id' => 119],
            ['parish' => 'Tocuyo de la Costa', 'municipality_id' => 119],
            ['parish' => 'Palmasola', 'municipality_id' => 120],
            ['parish' => 'Cabure', 'municipality_id' => 121],
            ['parish' => 'Colina', 'municipality_id' => 121],
            ['parish' => 'Curimagua', 'municipality_id' => 121],
            ['parish' => 'San José de la Costa', 'municipality_id' => 122],
            ['parish' => 'Píritu', 'municipality_id' => 122],
            ['parish' => 'San Francisco', 'municipality_id' => 123],
            ['parish' => 'Sucre', 'municipality_id' => 124],
            ['parish' => 'Pecaya', 'municipality_id' => 124],
            ['parish' => 'Tocópero', 'municipality_id' => 125],
            ['parish' => 'El Charal', 'municipality_id' => 126],
            ['parish' => 'Las Vegas del Tuy', 'municipality_id' => 126],
            ['parish' => 'Santa Cruz de Bucaral', 'municipality_id' => 126],
            ['parish' => 'Bruzual', 'municipality_id' => 127],
            ['parish' => 'Urumaco', 'municipality_id' => 127],
            ['parish' => 'Puerto Cumarebo', 'municipality_id' => 128],
            ['parish' => 'La Ciénaga', 'municipality_id' => 128],
            ['parish' => 'La Soledad', 'municipality_id' => 128],
            ['parish' => 'Pueblo Cumarebo', 'municipality_id' => 128],
            ['parish' => 'Zazárida', 'municipality_id' => 128],
            ['parish' => 'Churuguara', 'municipality_id' => 113],
            ['parish' => 'Camaguán', 'municipality_id' => 129],
            ['parish' => 'Puerto Miranda', 'municipality_id' => 129],
            ['parish' => 'Uverito', 'municipality_id' => 129],
            ['parish' => 'Chaguaramas', 'municipality_id' => 130],
            ['parish' => 'El Socorro', 'municipality_id' => 131],
            ['parish' => 'Tucupido', 'municipality_id' => 132],
            ['parish' => 'San Rafael de Laya', 'municipality_id' => 132],
            ['parish' => 'Altagracia de Orituco', 'municipality_id' => 133],
            ['parish' => 'San Rafael de Orituco', 'municipality_id' => 133],
            ['parish' => 'San Francisco Javier de Lezama', 'municipality_id' => 133],
            ['parish' => 'Paso Real de Macaira', 'municipality_id' => 133],
            ['parish' => 'Carlos Soublette', 'municipality_id' => 133],
            ['parish' => 'San Francisco de Macaira', 'municipality_id' => 133],
            ['parish' => 'Libertad de Orituco', 'municipality_id' => 133],
            ['parish' => 'Cantaclaro', 'municipality_id' => 134],
            ['parish' => 'San Juan de los Morros', 'municipality_id' => 134],
            ['parish' => 'Parapara', 'municipality_id' => 134],
            ['parish' => 'El Sombrero', 'municipality_id' => 135],
            ['parish' => 'Sosa', 'municipality_id' => 135],
            ['parish' => 'Las Mercedes', 'municipality_id' => 136],
            ['parish' => 'Cabruta', 'municipality_id' => 136],
            ['parish' => 'Santa Rita de Manapire', 'municipality_id' => 136],
            ['parish' => 'Valle de la Pascua', 'municipality_id' => 137],
            ['parish' => 'Espino', 'municipality_id' => 137],
            ['parish' => 'San José de Unare', 'municipality_id' => 138],
            ['parish' => 'Zaraza', 'municipality_id' => 138],
            ['parish' => 'San José de Tiznados', 'municipality_id' => 139],
            ['parish' => 'San Francisco de Tiznados', 'municipality_id' => 139],
            ['parish' => 'San Lorenzo de Tiznados', 'municipality_id' => 139],
            ['parish' => 'Ortiz', 'municipality_id' => 139],
            ['parish' => 'Guayabal', 'municipality_id' => 140],
            ['parish' => 'Cazorla', 'municipality_id' => 140],
            ['parish' => 'San José de Guaribe', 'municipality_id' => 141],
            ['parish' => 'Uveral', 'municipality_id' => 141],
            ['parish' => 'Santa María de Ipire', 'municipality_id' => 142],
            ['parish' => 'Altamira', 'municipality_id' => 142],
            ['parish' => 'El Calvario', 'municipality_id' => 143],
            ['parish' => 'El Rastro', 'municipality_id' => 143],
            ['parish' => 'Guardatinajas', 'municipality_id' => 143],
            ['parish' => 'Capital Urbana Calabozo', 'municipality_id' => 143],
            ['parish' => 'Quebrada Honda de Guache', 'municipality_id' => 144],
            ['parish' => 'Pío Tamayo', 'municipality_id' => 144],
            ['parish' => 'Yacambú', 'municipality_id' => 144],
            ['parish' => 'Fréitez', 'municipality_id' => 145],
            ['parish' => 'José María Blanco', 'municipality_id' => 145],
            ['parish' => 'Catedral', 'municipality_id' => 146],
            ['parish' => 'Concepción', 'municipality_id' => 146],
            ['parish' => 'El Cují', 'municipality_id' => 146],
            ['parish' => 'Juan de Villegas', 'municipality_id' => 146],
            ['parish' => 'Santa Rosa', 'municipality_id' => 146],
            ['parish' => 'Tamaca', 'municipality_id' => 146],
            ['parish' => 'Unión', 'municipality_id' => 146],
            ['parish' => 'Aguedo Felipe Alvarado', 'municipality_id' => 146],
            ['parish' => 'Buena Vista', 'municipality_id' => 146],
            ['parish' => 'Juárez', 'municipality_id' => 146],
            ['parish' => 'Juan Bautista Rodríguez', 'municipality_id' => 147],
            ['parish' => 'Cuara', 'municipality_id' => 147],
            ['parish' => 'Diego de Lozada', 'municipality_id' => 147],
            ['parish' => 'Paraíso de San José', 'municipality_id' => 147],
            ['parish' => 'San Miguel', 'municipality_id' => 147],
            ['parish' => 'Tintorero', 'municipality_id' => 147],
            ['parish' => 'José Bernardo Dorante', 'municipality_id' => 147],
            ['parish' => 'Coronel Mariano Per', 'municipality_id' => 147],
            ['parish' => 'Bolívar', 'municipality_id' =>148],
            ['parish' => 'Anzoátegui', 'municipality_id' => 148],
            ['parish' => 'Guarico', 'municipality_id' => 148],
            ['parish' => 'Hilario Luna y Luna', 'municipality_id' => 148],
            ['parish' => 'Humocaro Alto', 'municipality_id' => 148],
            ['parish' => 'Humocaro Bajo', 'municipality_id' => 148],
            ['parish' => 'La Candelaria', 'municipality_id' => 148],
            ['parish' => 'Morán', 'municipality_id' => 148],
            ['parish' => 'Cabudare', 'municipality_id' => 149],
            ['parish' => 'José Gregorio Bastidas', 'municipality_id' => 149],
            ['parish' => 'Agua Viva', 'municipality_id' => 149],
            ['parish' => 'Sarare', 'municipality_id' => 150],
            ['parish' => 'Buría', 'municipality_id' => 150],
            ['parish' => 'Gustavo Vegas León', 'municipality_id' => 150],
            ['parish' => 'Trinidad Samuel', 'municipality_id' => 151],
            ['parish' => 'Antonio Díaz', 'municipality_id' => 151],
            ['parish' => 'Camacaro', 'municipality_id' => 151],
            ['parish' => 'Castañeda', 'municipality_id' => 151],
            ['parish' => 'Cecilio Zubillaga', 'municipality_id' => 151],
            ['parish' => 'Chiquinquirá', 'municipality_id' => 151],
            ['parish' => 'El Blanco', 'municipality_id' => 151],
            ['parish' => 'Espinoza de los Monteros', 'municipality_id' => 151],
            ['parish' => 'Lara', 'municipality_id' => 151],
            ['parish' => 'Las Mercedes', 'municipality_id' => 151],
            ['parish' => 'Manuel Morillo', 'municipality_id' => 151],
            ['parish' => 'Montaña Verde', 'municipality_id' => 151],
            ['parish' => 'Montes de Oca', 'municipality_id' => 151],
            ['parish' => 'Torres', 'municipality_id' => 151],
            ['parish' => 'Heriberto Arroyo', 'municipality_id' => 151],
            ['parish' => 'Reyes Vargas', 'municipality_id' => 151],
            ['parish' => 'Altagracia', 'municipality_id' => 151],
            ['parish' => 'Siquisique', 'municipality_id' => 152],
            ['parish' => 'Moroturo', 'municipality_id' => 152],
            ['parish' => 'San Miguel', 'municipality_id' => 152],
            ['parish' => 'Xaguas', 'municipality_id' => 152],
            ['parish' => 'Presidente Betancourt', 'municipality_id' => 179],
            ['parish' => 'Presidente Páez', 'municipality_id' => 179],
            ['parish' => 'Presidente Rómulo Gallegos', 'municipality_id' => 179],
            ['parish' => 'Gabriel Picón González', 'municipality_id' => 179],
            ['parish' => 'Héctor Amable Mora', 'municipality_id' => 179],
            ['parish' => 'José Nucete Sardi', 'municipality_id' => 179],
            ['parish' => 'Pulido Méndez', 'municipality_id' => 179],
            ['parish' => 'La Azulita', 'municipality_id' => 180],
            ['parish' => 'Santa Cruz de Mora', 'municipality_id' => 181],
            ['parish' => 'Mesa Bolívar', 'municipality_id' => 181],
            ['parish' => 'Mesa de Las Palmas', 'municipality_id' => 181],
            ['parish' => 'Aricagua', 'municipality_id' => 182],
            ['parish' => 'San Antonio', 'municipality_id' => 182],
            ['parish' => 'Canagua', 'municipality_id' => 183],
            ['parish' => 'Capurí', 'municipality_id' => 183],
            ['parish' => 'Chacantá', 'municipality_id' => 183],
            ['parish' => 'El Molino', 'municipality_id' => 183],
            ['parish' => 'Guaimaral', 'municipality_id' => 183],
            ['parish' => 'Mucutuy', 'municipality_id' => 183],
            ['parish' => 'Mucuchachí', 'municipality_id' => 183],
            ['parish' => 'Fernández Peña', 'municipality_id' => 184],
            ['parish' => 'Matriz', 'municipality_id' => 184],
            ['parish' => 'Montalbán', 'municipality_id' => 184],
            ['parish' => 'Acequias', 'municipality_id' => 184],
            ['parish' => 'Jají', 'municipality_id' => 184],
            ['parish' => 'La Mesa', 'municipality_id' => 184],
            ['parish' => 'San José del Sur', 'municipality_id' => 184],
            ['parish' => 'Tucaní', 'municipality_id' => 185],
            ['parish' => 'Florencio Ramírez', 'municipality_id' => 185],
            ['parish' => 'Santo Domingo', 'municipality_id' => 186],
            ['parish' => 'Las Piedras', 'municipality_id' => 186],
            ['parish' => 'Guaraque', 'municipality_id' => 187],
            ['parish' => 'Mesa de Quintero', 'municipality_id' => 187],
            ['parish' => 'Río Negro', 'municipality_id' => 187],
            ['parish' => 'Arapuey', 'municipality_id' => 188],
            ['parish' => 'Palmira', 'municipality_id' => 188],
            ['parish' => 'San Cristóbal de Torondoy', 'municipality_id' => 189],
            ['parish' => 'Torondoy', 'municipality_id' => 189],
            ['parish' => 'Antonio Spinetti Dini', 'municipality_id' => 190],
            ['parish' => 'Arias', 'municipality_id' => 190],
            ['parish' => 'Caracciolo Parra Pérez', 'municipality_id' => 190],
            ['parish' => 'Domingo Peña', 'municipality_id' => 190],
            ['parish' => 'El Llano', 'municipality_id' => 190],
            ['parish' => 'Gonzalo Picón Febres', 'municipality_id' => 190],
            ['parish' => 'Jacinto Plaza', 'municipality_id' => 190],
            ['parish' => 'Juan Rodríguez Suárez', 'municipality_id' => 190],
            ['parish' => 'Lasso de la Vega', 'municipality_id' => 190],
            ['parish' => 'Mariano Picón Salas', 'municipality_id' => 190],
            ['parish' => 'Milla', 'municipality_id' => 190],
            ['parish' => 'Osuna Rodríguez', 'municipality_id' => 190],
            ['parish' => 'Sagrario', 'municipality_id' => 190],
            ['parish' => 'El Morro', 'municipality_id' => 190],
            ['parish' => 'Los Nevados', 'municipality_id' => 190],
            ['parish' => 'Andrés Eloy Blanco', 'municipality_id' => 191],
            ['parish' => 'La Venta', 'municipality_id' => 191],
            ['parish' => 'Piñango', 'municipality_id' => 191],
            ['parish' => 'Timotes', 'municipality_id' => 191],
            ['parish' => 'Eloy Paredes', 'municipality_id' => 192],
            ['parish' => 'San Rafael de Alcázar', 'municipality_id' => 192],
            ['parish' => 'Santa Elena de Arenales', 'municipality_id' => 192],
            ['parish' => 'Santa María de Caparo', 'municipality_id' => 193],
            ['parish' => 'Pueblo Llano', 'municipality_id' => 194],
            ['parish' => 'Cacute', 'municipality_id' => 195],
            ['parish' => 'La Toma', 'municipality_id' => 195],
            ['parish' => 'Mucuchíes', 'municipality_id' => 195],
            ['parish' => 'Mucurubá', 'municipality_id' => 195],
            ['parish' => 'San Rafael', 'municipality_id' => 195],
            ['parish' => 'Gerónimo Maldonado', 'municipality_id' => 196],
            ['parish' => 'Bailadores', 'municipality_id' => 196],
            ['parish' => 'Tabay', 'municipality_id' => 197],
            ['parish' => 'Chiguará', 'municipality_id' => 198],
            ['parish' => 'Estánquez', 'municipality_id' => 198],
            ['parish' => 'Lagunillas', 'municipality_id' => 198],
            ['parish' => 'La Trampa', 'municipality_id' => 198],
            ['parish' => 'Pueblo Nuevo del Sur', 'municipality_id' => 198],
            ['parish' => 'San Juan', 'municipality_id' => 198],
            ['parish' => 'El Amparo', 'municipality_id' => 199],
            ['parish' => 'El Llano', 'municipality_id' => 199],
            ['parish' => 'San Francisco', 'municipality_id' => 199],
            ['parish' => 'Tovar', 'municipality_id' => 199],
            ['parish' => 'Independencia', 'municipality_id' => 200],
            ['parish' => 'María de la Concepción Palacios Blanco', 'municipality_id' => 200],
            ['parish' => 'Nueva Bolivia', 'municipality_id' => 200],
            ['parish' => 'Santa Apolonia', 'municipality_id' => 200],
            ['parish' => 'Caño El Tigre', 'municipality_id' => 201],
            ['parish' => 'Zea', 'municipality_id' => 201],
            ['parish' => 'Aragüita', 'municipality_id' => 223],
            ['parish' => 'Arévalo González', 'municipality_id' => 223],
            ['parish' => 'Capaya', 'municipality_id' => 223],
            ['parish' => 'Caucagua', 'municipality_id' => 223],
            ['parish' => 'Panaquire', 'municipality_id' => 223],
            ['parish' => 'Ribas', 'municipality_id' => 223],
            ['parish' => 'El Café', 'municipality_id' => 223],
            ['parish' => 'Marizapa', 'municipality_id' => 223],
            ['parish' => 'Cumbo', 'municipality_id' => 224],
            ['parish' => 'San José de Barlovento', 'municipality_id' => 224],
            ['parish' => 'El Cafetal', 'municipality_id' => 225],
            ['parish' => 'Las Minas', 'municipality_id' => 225],
            ['parish' => 'Nuestra Señora del Rosario', 'municipality_id' => 225],
            ['parish' => 'Higuerote', 'municipality_id' => 226],
            ['parish' => 'Curiepe', 'municipality_id' => 226],
            ['parish' => 'Tacarigua de Brión', 'municipality_id' => 226],
            ['parish' => 'Mamporal', 'municipality_id' => 227],
            ['parish' => 'Carrizal', 'municipality_id' => 228],
            ['parish' => 'Chacao', 'municipality_id' => 229],
            ['parish' => 'Charallave', 'municipality_id' => 230],
            ['parish' => 'Las Brisas', 'municipality_id' => 230],
            ['parish' => 'El Hatillo', 'municipality_id' => 231],
            ['parish' => 'Altagracia de la Montaña', 'municipality_id' => 232],
            ['parish' => 'Cecilio Acosta', 'municipality_id' => 232],
            ['parish' => 'Los Teques', 'municipality_id' => 232],
            ['parish' => 'El Jarillo', 'municipality_id' => 232],
            ['parish' => 'San Pedro', 'municipality_id' => 232],
            ['parish' => 'Tácata', 'municipality_id' => 232],
            ['parish' => 'Paracotos', 'municipality_id' => 232],
            ['parish' => 'Cartanal', 'municipality_id' => 233],
            ['parish' => 'Santa Teresa del Tuy', 'municipality_id' => 233],
            ['parish' => 'La Democracia', 'municipality_id' => 234],
            ['parish' => 'Ocumare del Tuy', 'municipality_id' => 234],
            ['parish' => 'Santa Bárbara', 'municipality_id' => 234],
            ['parish' => 'San Antonio de los Altos', 'municipality_id' => 235],
            ['parish' => 'Río Chico', 'municipality_id' => 236],
            ['parish' => 'El Guapo', 'municipality_id' => 236],
            ['parish' => 'Tacarigua de la Laguna', 'municipality_id' => 236],
            ['parish' => 'Paparo', 'municipality_id' => 236],
            ['parish' => 'San Fernando del Guapo', 'municipality_id' => 236],
            ['parish' => 'Santa Lucía del Tuy', 'municipality_id' => 237],
            ['parish' => 'Cúpira', 'municipality_id' => 238],
            ['parish' => 'Machurucuto', 'municipality_id' => 238],
            ['parish' => 'Guarenas', 'municipality_id' => 239],
            ['parish' => 'San Antonio de Yare', 'municipality_id' => 240],
            ['parish' => 'San Francisco de Yare', 'municipality_id' => 240],
            ['parish' => 'Leoncio Martínez', 'municipality_id' => 241],
            ['parish' => 'Petare', 'municipality_id' => 241],
            ['parish' => 'Caucagüita', 'municipality_id' => 241],
            ['parish' => 'Filas de Mariche', 'municipality_id' => 241],
            ['parish' => 'La Dolorita', 'municipality_id' => 241],
            ['parish' => 'Cúa', 'municipality_id' => 242],
            ['parish' => 'Nueva Cúa', 'municipality_id' => 242],
            ['parish' => 'Guatire', 'municipality_id' => 243],
            ['parish' => 'Bolívar', 'municipality_id' => 243],
            ['parish' => 'San Antonio de Maturín', 'municipality_id' => 258],
            ['parish' => 'San Francisco de Maturín', 'municipality_id' => 258],
            ['parish' => 'Aguasay', 'municipality_id' => 259],
            ['parish' => 'Caripito', 'municipality_id' => 260],
            ['parish' => 'El Guácharo', 'municipality_id' => 261],
            ['parish' => 'La Guanota', 'municipality_id' => 261],
            ['parish' => 'Sabana de Piedra', 'municipality_id' => 261],
            ['parish' => 'San Agustín', 'municipality_id' => 261],
            ['parish' => 'Teresen', 'municipality_id' => 261],
            ['parish' => 'Caripe', 'municipality_id' => 261],
            ['parish' => 'Areo', 'municipality_id' => 262],
            ['parish' => 'Capital Cedeño', 'municipality_id' => 262],
            ['parish' => 'San Félix de Cantalicio', 'municipality_id' => 262],
            ['parish' => 'Viento Fresco', 'municipality_id' => 262],
            ['parish' => 'El Tejero', 'municipality_id' => 263],
            ['parish' => 'Punta de Mata', 'municipality_id' => 263],
            ['parish' => 'Chaguaramas', 'municipality_id' => 264],
            ['parish' => 'Las Alhuacas', 'municipality_id' => 264],
            ['parish' => 'Tabasca', 'municipality_id' => 264],
            ['parish' => 'Temblador', 'municipality_id' => 264],
            ['parish' => 'Alto de los Godos', 'municipality_id' => 265],
            ['parish' => 'Boquerón', 'municipality_id' => 265],
            ['parish' => 'Las Cocuizas', 'municipality_id' => 265],
            ['parish' => 'La Cruz', 'municipality_id' => 265],
            ['parish' => 'San Simón', 'municipality_id' => 265],
            ['parish' => 'El Corozo', 'municipality_id' => 265],
            ['parish' => 'El Furrial', 'municipality_id' => 265],
            ['parish' => 'Jusepín', 'municipality_id' => 265],
            ['parish' => 'La Pica', 'municipality_id' => 265],
            ['parish' => 'San Vicente', 'municipality_id' => 265],
            ['parish' => 'Aparicio', 'municipality_id' => 266],
            ['parish' => 'Aragua de Maturín', 'municipality_id' => 266],
            ['parish' => 'Chaguamal', 'municipality_id' => 266],
            ['parish' => 'El Pinto', 'municipality_id' => 266],
            ['parish' => 'Guanaguana', 'municipality_id' => 266],
            ['parish' => 'La Toscana', 'municipality_id' => 266],
            ['parish' => 'Taguaya', 'municipality_id' => 266],
            ['parish' => 'Cachipo', 'municipality_id' => 267],
            ['parish' => 'Quiriquire', 'municipality_id' => 267],
            ['parish' => 'Santa Bárbara', 'municipality_id' => 268],
            ['parish' => 'Barrancas', 'municipality_id' => 269],
            ['parish' => 'Los Barrancos de Fajardo', 'municipality_id' => 269],
            ['parish' => 'Uracoa', 'municipality_id' => 270],
            ['parish' => 'Antolín del Campo', 'municipality_id' => 271],
            ['parish' => 'Arismendi', 'municipality_id' => 272],
            ['parish' => 'García', 'municipality_id' => 273],
            ['parish' => 'Francisco Fajardo', 'municipality_id' => 273],
            ['parish' => 'Bolívar', 'municipality_id' => 274],
            ['parish' => 'Guevara', 'municipality_id' => 274],
            ['parish' => 'Matasiete', 'municipality_id' => 274],
            ['parish' => 'Santa Ana', 'municipality_id' => 274],
            ['parish' => 'Sucre', 'municipality_id' => 274],
            ['parish' => 'Aguirre', 'municipality_id' => 275],
            ['parish' => 'Maneiro', 'municipality_id' => 275],
            ['parish' => 'Adrián', 'municipality_id' => 276],
            ['parish' => 'Juan Griego', 'municipality_id' => 276],
            ['parish' => 'Yaguaraparo', 'municipality_id' => 276],
            ['parish' => 'Porlamar', 'municipality_id' => 277],
            ['parish' => 'San Francisco de Macanao', 'municipality_id' => 278],
            ['parish' => 'Boca de Río', 'municipality_id' => 278],
            ['parish' => 'Tubores', 'municipality_id' => 279],
            ['parish' => 'Los Baleales', 'municipality_id' => 279],
            ['parish' => 'Vicente Fuentes', 'municipality_id' => 280],
            ['parish' => 'Villalba', 'municipality_id' => 280],
            ['parish' => 'San Juan Bautista', 'municipality_id' => 281],
            ['parish' => 'Zabala', 'municipality_id' => 281],
            ['parish' => 'Capital Araure', 'municipality_id' => 283],
            ['parish' => 'Río Acarigua', 'municipality_id' => 283],
            ['parish' => 'Capital Esteller', 'municipality_id' => 284],
            ['parish' => 'Uveral', 'municipality_id' => 284],
            ['parish' => 'Guanare', 'municipality_id' => 285],
            ['parish' => 'Córdoba', 'municipality_id' => 285],
            ['parish' => 'San José de la Montaña', 'municipality_id' => 285],
            ['parish' => 'San Juan de Guanaguanare', 'municipality_id' => 285],
            ['parish' => 'Virgen de la Coromoto', 'municipality_id' => 285],
            ['parish' => 'Guanarito', 'municipality_id' => 286],
            ['parish' => 'Trinidad de la Capilla', 'municipality_id' => 286],
            ['parish' => 'Divina Pastora', 'municipality_id' => 286],
            ['parish' => 'Monseñor José Vicente de Unda', 'municipality_id' => 287],
            ['parish' => 'Peña Blanca', 'municipality_id' => 287],
            ['parish' => 'Capital Ospino', 'municipality_id' => 288],
            ['parish' => 'Aparición', 'municipality_id' => 288],
            ['parish' => 'La Estación', 'municipality_id' => 288],
            ['parish' => 'Páez', 'municipality_id' => 289],
            ['parish' => 'Payara', 'municipality_id' => 289],
            ['parish' => 'Pimpinela', 'municipality_id' => 289],
            ['parish' => 'Ramón Peraza', 'municipality_id' => 289],
            ['parish' => 'Papelón', 'municipality_id' => 290],
            ['parish' => 'Caño Delgadito', 'municipality_id' => 290],
            ['parish' => 'San Genaro de Boconoito', 'municipality_id' => 291],
            ['parish' => 'Antolín Tovar', 'municipality_id' => 291],
            ['parish' => 'San Rafael de Onoto', 'municipality_id' => 292],
            ['parish' => 'Santa Fe', 'municipality_id' => 292],
            ['parish' => 'Thermo Morles', 'municipality_id' => 292],
            ['parish' => 'Santa Rosalía', 'municipality_id' => 293],
            ['parish' => 'Florida', 'municipality_id' => 293],
            ['parish' => 'Sucre', 'municipality_id' => 294],
            ['parish' => 'Concepción', 'municipality_id' => 294],
            ['parish' => 'San Rafael de Palo Alzado', 'municipality_id' => 294],
            ['parish' => 'Uvencio Antonio Velásquez', 'municipality_id' => 294],
            ['parish' => 'San José de Saguaz', 'municipality_id' => 294],
            ['parish' => 'Villa Rosa', 'municipality_id' => 294],
            ['parish' => 'Turén', 'municipality_id' => 295],
            ['parish' => 'Canelones', 'municipality_id' => 295],
            ['parish' => 'Santa Cruz', 'municipality_id' => 295],
            ['parish' => 'San Isidro Labrador', 'municipality_id' => 295],
            ['parish' => 'Mariño', 'municipality_id' => 296],
            ['parish' => 'Rómulo Gallegos', 'municipality_id' => 296],
            ['parish' => 'San José de Aerocuar', 'municipality_id' => 297],
            ['parish' => 'Tavera Acosta', 'municipality_id' => 297],
            ['parish' => 'Río Caribe', 'municipality_id' => 298],
            ['parish' => 'Antonio José de Sucre', 'municipality_id' => 298],
            ['parish' => 'El Morro de Puerto Santo', 'municipality_id' => 298],
            ['parish' => 'Puerto Santo', 'municipality_id' => 298],
            ['parish' => 'San Juan de las Galdonas', 'municipality_id' => 298],
            ['parish' => 'El Pilar', 'municipality_id' => 299],
            ['parish' => 'El Rincón', 'municipality_id' => 299],
            ['parish' => 'General Francisco Antonio Váquez', 'municipality_id' => 299],
            ['parish' => 'Guaraúnos', 'municipality_id' => 299],
            ['parish' => 'Tunapuicito', 'municipality_id' => 299],
            ['parish' => 'Unión', 'municipality_id' => 299],
            ['parish' => 'Santa Catalina', 'municipality_id' => 300],
            ['parish' => 'Santa Rosa', 'municipality_id' => 300],
            ['parish' => 'Santa Teresa', 'municipality_id' => 300],
            ['parish' => 'Bolívar', 'municipality_id' => 300],
            ['parish' => 'Maracapana', 'municipality_id' => 300],
            ['parish' => 'Libertad', 'municipality_id' => 302],
            ['parish' => 'El Paujil', 'municipality_id' => 302],
            ['parish' => 'Yaguaraparo', 'municipality_id' => 302],
            ['parish' => 'Cruz Salmerón Acosta', 'municipality_id' => 303],
            ['parish' => 'Chacopata', 'municipality_id' => 303],
            ['parish' => 'Manicuare', 'municipality_id' => 303],
            ['parish' => 'Tunapuy', 'municipality_id' => 304],
            ['parish' => 'Campo Elías', 'municipality_id' => 304],
            ['parish' => 'Irapa', 'municipality_id' => 305],
            ['parish' => 'Campo Claro', 'municipality_id' => 305],
            ['parish' => 'Maraval', 'municipality_id' => 305],
            ['parish' => 'San Antonio de Irapa', 'municipality_id' => 305],
            ['parish' => 'Soro', 'municipality_id' => 305],
            ['parish' => 'Mejía', 'municipality_id' => 306],
            ['parish' => 'Cumanacoa', 'municipality_id' => 307],
            ['parish' => 'Arenas', 'municipality_id' => 307],
            ['parish' => 'Aricagua', 'municipality_id' => 307],
            ['parish' => 'Cogollar', 'municipality_id' => 307],
            ['parish' => 'San Fernando', 'municipality_id' => 307],
            ['parish' => 'San Lorenzo', 'municipality_id' => 307],
            ['parish' => 'Villa Frontado e de Cariaco)', 'municipality_id' => 308],
            ['parish' => 'Catuaro', 'municipality_id' => 308],
            ['parish' => 'Rendón', 'municipality_id' => 308],
            ['parish' => 'San Cruz', 'municipality_id' => 308],
            ['parish' => 'Santa María', 'municipality_id' => 308],
            ['parish' => 'Altagracia', 'municipality_id' => 309],
            ['parish' => 'Santa Inés', 'municipality_id' => 309],
            ['parish' => 'Valentín Valiente', 'municipality_id' => 309],
            ['parish' => 'Ayacucho', 'municipality_id' => 309],
            ['parish' => 'San Juan', 'municipality_id' => 309],
            ['parish' => 'Raúl Leoni', 'municipality_id' => 309],
            ['parish' => 'Gran Mariscal', 'municipality_id' => 309],
            ['parish' => 'Cristóbal Colón', 'municipality_id' => 310],
            ['parish' => 'Bideau', 'municipality_id' => 310],
            ['parish' => 'Punta de Piedras', 'municipality_id' => 310],
            ['parish' => 'Güiria', 'municipality_id' => 310],
            ['parish' => 'Andrés Bello', 'municipality_id' => 341],
            ['parish' => 'Antonio Rómulo Costa', 'municipality_id' => 342],
            ['parish' => 'Ayacucho', 'municipality_id' => 343],
            ['parish' => 'Rivas Berti', 'municipality_id' => 343],
            ['parish' => 'San Pedro del Río', 'municipality_id' => 343],
            ['parish' => 'Bolívar', 'municipality_id' => 344],
            ['parish' => 'Palotal', 'municipality_id' => 344],
            ['parish' => 'General Juan Vicente Gómez', 'municipality_id' => 344],
            ['parish' => 'Isaías Medina Angarita', 'municipality_id' => 344],
            ['parish' => 'Cárdenas', 'municipality_id' => 345],
            ['parish' => 'Amenodoro Ángel Lamus', 'municipality_id' => 345],
            ['parish' => 'La Florida', 'municipality_id' => 345],
            ['parish' => 'Córdoba', 'municipality_id' => 346],
            ['parish' => 'Fernández Feo', 'municipality_id' => 347],
            ['parish' => 'Alberto Adriani', 'municipality_id' => 347],
            ['parish' => 'Santo Domingo', 'municipality_id' => 347],
            ['parish' => 'Francisco de Miranda', 'municipality_id' => 348],
            ['parish' => 'García de Hevia', 'municipality_id' => 349],
            ['parish' => 'Boca de Grita', 'municipality_id' => 349],
            ['parish' => 'José Antonio Páez', 'municipality_id' => 349],
            ['parish' => 'Guásimos', 'municipality_id' => 350],
            ['parish' => 'Independencia', 'municipality_id' => 351],
            ['parish' => 'Juan Germán Roscio', 'municipality_id' => 351],
            ['parish' => 'Román Cárdenas', 'municipality_id' => 351],
            ['parish' => 'Jáuregui', 'municipality_id' => 352],
            ['parish' => 'Emilio Constantino Guerrero', 'municipality_id' => 352],
            ['parish' => 'Monseñor Miguel Antonio Salas', 'municipality_id' => 352],
            ['parish' => 'José María Vargas', 'municipality_id' => 353],
            ['parish' => 'Junín', 'municipality_id' => 354],
            ['parish' => 'La Petrólea', 'municipality_id' => 354],
            ['parish' => 'Quinimarí', 'municipality_id' => 354],
            ['parish' => 'Bramón', 'municipality_id' => 354],
            ['parish' => 'Libertad', 'municipality_id' => 355],
            ['parish' => 'Cipriano Castro', 'municipality_id' => 355],
            ['parish' => 'Manuel Felipe Rugeles', 'municipality_id' => 355],
            ['parish' => 'Libertador', 'municipality_id' => 356],
            ['parish' => 'Doradas', 'municipality_id' => 356],
            ['parish' => 'Emeterio Ochoa', 'municipality_id' => 356],
            ['parish' => 'San Joaquín de Navay', 'municipality_id' => 356],
            ['parish' => 'Lobatera', 'municipality_id' => 357],
            ['parish' => 'Constitución', 'municipality_id' => 357],
            ['parish' => 'Michelena', 'municipality_id' => 358],
            ['parish' => 'Panamericano', 'municipality_id' => 359],
            ['parish' => 'La Palmita', 'municipality_id' => 359],
            ['parish' => 'Pedro María Ureña', 'municipality_id' => 360],
            ['parish' => 'Nueva Arcadia', 'municipality_id' => 360],
            ['parish' => 'Delicias', 'municipality_id' => 361],
            ['parish' => 'Pecaya', 'municipality_id' => 361],
            ['parish' => 'Samuel Darío Maldonado', 'municipality_id' => 362],
            ['parish' => 'Boconó', 'municipality_id' => 362],
            ['parish' => 'Hernández', 'municipality_id' => 362],
            ['parish' => 'La Concordia', 'municipality_id' => 363],
            ['parish' => 'San Juan Bautista', 'municipality_id' => 363],
            ['parish' => 'Pedro María Morantes', 'municipality_id' => 363],
            ['parish' => 'San Sebastián', 'municipality_id' => 363],
            ['parish' => 'Dr. Francisco Romero Lobo', 'municipality_id' => 363],
            ['parish' => 'Seboruco', 'municipality_id' => 364],
            ['parish' => 'Simón Rodríguez', 'municipality_id' => 365],
            ['parish' => 'Sucre', 'municipality_id' => 366],
            ['parish' => 'Eleazar López Contreras', 'municipality_id' => 366],
            ['parish' => 'San Pablo', 'municipality_id' => 366],
            ['parish' => 'Torbes', 'municipality_id' => 367],
            ['parish' => 'Uribante', 'municipality_id' => 368],
            ['parish' => 'Cárdenas', 'municipality_id' => 368],
            ['parish' => 'Juan Pablo Peñalosa', 'municipality_id' => 368],
            ['parish' => 'Potosí', 'municipality_id' => 368],
            ['parish' => 'San Judas Tadeo', 'municipality_id' => 369],
            ['parish' => 'Araguaney', 'municipality_id' => 370],
            ['parish' => 'El Jaguito', 'municipality_id' => 370],
            ['parish' => 'La Esperanza', 'municipality_id' => 370],
            ['parish' => 'Santa Isabel', 'municipality_id' => 370],
            ['parish' => 'Boconó', 'municipality_id' => 371],
            ['parish' => 'El Carmen', 'municipality_id' => 371],
            ['parish' => 'Mosquey', 'municipality_id' => 371],
            ['parish' => 'Ayacucho', 'municipality_id' => 371],
            ['parish' => 'Burbusay', 'municipality_id' => 371],
            ['parish' => 'General Ribas', 'municipality_id' => 371],
            ['parish' => 'Guaramacal', 'municipality_id' => 371],
            ['parish' => 'Vega de Guaramacal', 'municipality_id' => 371],
            ['parish' => 'Monseñor Jáuregui', 'municipality_id' => 371],
            ['parish' => 'Rafael Rangel', 'municipality_id' => 371],
            ['parish' => 'San Miguel', 'municipality_id' => 371],
            ['parish' => 'San José', 'municipality_id' => 371],
            ['parish' => 'Sabana Grande', 'municipality_id' => 372],
            ['parish' => 'Cheregüé', 'municipality_id' => 372],
            ['parish' => 'Granados', 'municipality_id' => 372],
            ['parish' => 'Arnoldo Gabaldón', 'municipality_id' => 373],
            ['parish' => 'Bolivia', 'municipality_id' => 373],
            ['parish' => 'Carrillo', 'municipality_id' => 373],
            ['parish' => 'Cegarra', 'municipality_id' => 373],
            ['parish' => 'Chejendé', 'municipality_id' => 373],
            ['parish' => 'Manuel Salvador Ulloa', 'municipality_id' => 373],
            ['parish' => 'San José', 'municipality_id' => 373],
            ['parish' => 'Carache', 'municipality_id' => 374],
            ['parish' => 'La Concepción', 'municipality_id' => 374],
            ['parish' => 'Cuicas', 'municipality_id' => 374],
            ['parish' => 'Panamericana', 'municipality_id' => 374],
            ['parish' => 'Santa Cruz', 'municipality_id' => 374],
            ['parish' => 'Escuque', 'municipality_id' => 375],
            ['parish' => 'La Unión', 'municipality_id' => 375],
            ['parish' => 'Santa Rita', 'municipality_id' => 375],
            ['parish' => 'Sabana Libre', 'municipality_id' => 375],
            ['parish' => 'El Socorro', 'municipality_id' => 376],
            ['parish' => 'Los Caprichos', 'municipality_id' => 376],
            ['parish' => 'Antonio José de Sucre', 'municipality_id' => 376],
            ['parish' => 'Campo Elías', 'municipality_id' => 377],
            ['parish' => 'Arnoldo Gabaldón', 'municipality_id' => 377],
            ['parish' => 'Santa Apolonia', 'municipality_id' => 378],
            ['parish' => 'El Progreso', 'municipality_id' => 378],
            ['parish' => 'La Ceiba', 'municipality_id' => 378],
            ['parish' => 'Tres de Febrero', 'municipality_id' => 378],
            ['parish' => 'El Dividive', 'municipality_id' => 379],
            ['parish' => 'Agua Santa', 'municipality_id' => 379],
            ['parish' => 'Agua Caliente', 'municipality_id' => 379],
            ['parish' => 'El Cenizo', 'municipality_id' => 379],
            ['parish' => 'Valerita', 'municipality_id' => 379],
            ['parish' => 'Monte Carmelo', 'municipality_id' => 380],
            ['parish' => 'Buena Vista', 'municipality_id' => 380],
            ['parish' => 'Santa María del Horcón', 'municipality_id' => 380],
            ['parish' => 'Motatán', 'municipality_id' => 381],
            ['parish' => 'El Baño', 'municipality_id' => 381],
            ['parish' => 'Jalisco', 'municipality_id' => 381],
            ['parish' => 'Pampán', 'municipality_id' => 382],
            ['parish' => 'Flor de Patria', 'municipality_id' => 382],
            ['parish' => 'La Paz', 'municipality_id' => 382],
            ['parish' => 'Santa Ana', 'municipality_id' => 382],
            ['parish' => 'Pampanito', 'municipality_id' => 383],
            ['parish' => 'La Concepción', 'municipality_id' => 383],
            ['parish' => 'Pampanito II', 'municipality_id' => 383],
            ['parish' => 'Betijoque', 'municipality_id' => 384],
            ['parish' => 'José Gregorio Hernández', 'municipality_id' => 384],
            ['parish' => 'La Pueblita', 'municipality_id' => 384],
            ['parish' => 'Los Cedros', 'municipality_id' => 384],
            ['parish' => 'Carvajal', 'municipality_id' => 385],
            ['parish' => 'Campo Alegre', 'municipality_id' => 385],
            ['parish' => 'Antonio Nicolás Briceño', 'municipality_id' => 385],
            ['parish' => 'José Leonardo Suárez', 'municipality_id' => 385],
            ['parish' => 'Sabana de Mendoza', 'municipality_id' => 386],
            ['parish' => 'Junín', 'municipality_id' => 386],
            ['parish' => 'Valmore Rodríguez', 'municipality_id' => 386],
            ['parish' => 'El Paraíso', 'municipality_id' => 386],
            ['parish' => 'Andrés Linares', 'municipality_id' => 387],
            ['parish' => 'Chiquinquirá', 'municipality_id' => 387],
            ['parish' => 'Cristóbal Mendoza', 'municipality_id' => 387],
            ['parish' => 'Cruz Carrillo', 'municipality_id' => 387],
            ['parish' => 'Matriz', 'municipality_id' => 387],
            ['parish' => 'Monseñor Carrillo', 'municipality_id' => 387],
            ['parish' => 'Tres Esquinas', 'municipality_id' => 387],
            ['parish' => 'Cabimbú', 'municipality_id' => 388],
            ['parish' => 'Jajó', 'municipality_id' => 388],
            ['parish' => 'La Mesa de Esnujaque', 'municipality_id' => 388],
            ['parish' => 'Santiago', 'municipality_id' => 388],
            ['parish' => 'Tuñame', 'municipality_id' => 388],
            ['parish' => 'La Quebrada', 'municipality_id' => 388],
            ['parish' => 'Juan Ignacio Montilla', 'municipality_id' => 389],
            ['parish' => 'La Beatriz', 'municipality_id' => 389],
            ['parish' => 'La Puerta', 'municipality_id' => 389],
            ['parish' => 'Mendoza del Valle de Momboy', 'municipality_id' => 389],
            ['parish' => 'Mercedes Díaz', 'municipality_id' => 389],
            ['parish' => 'San Luis', 'municipality_id' => 389],
            ['parish' => 'Caraballeda', 'municipality_id' => 390],
            ['parish' => 'Carayaca', 'municipality_id' => 390],
            ['parish' => 'Carlos Soublette', 'municipality_id' => 390],
            ['parish' => 'Caruao Chuspa', 'municipality_id' => 390],
            ['parish' => 'Catia La Mar', 'municipality_id' => 390],
            ['parish' => 'El Junko', 'municipality_id' => 390],
            ['parish' => 'La Guaira', 'municipality_id' => 390],
            ['parish' => 'Macuto', 'municipality_id' => 390],
            ['parish' => 'Maiquetía', 'municipality_id' => 390],
            ['parish' => 'Naiguatá', 'municipality_id' => 390],
            ['parish' => 'Urimare', 'municipality_id' => 390],
            ['parish' => 'Arístides Bastidas', 'municipality_id' => 391],
            ['parish' => 'Bolívar', 'municipality_id' => 392],
            ['parish' => 'Chivacoa', 'municipality_id' => 407],
            ['parish' => 'Campo Elías', 'municipality_id' => 407],
            ['parish' => 'Cocorote', 'municipality_id' => 408],
            ['parish' => 'Independencia', 'municipality_id' => 409],
            ['parish' => 'José Antonio Páez', 'municipality_id' => 410],
            ['parish' => 'La Trinidad', 'municipality_id' => 411],
            ['parish' => 'Manuel Monge', 'municipality_id' => 412],
            ['parish' => 'Salóm', 'municipality_id' => 413],
            ['parish' => 'Temerla', 'municipality_id' => 413],
            ['parish' => 'Nirgua', 'municipality_id' => 413],
            ['parish' => 'San Andrés', 'municipality_id' => 414],
            ['parish' => 'Yaritagua', 'municipality_id' => 414],
            ['parish' => 'San Javier', 'municipality_id' => 415],
            ['parish' => 'Albarico', 'municipality_id' => 415],
            ['parish' => 'San Felipe', 'municipality_id' => 415],
            ['parish' => 'Sucre', 'municipality_id' => 416],
            ['parish' => 'Urachiche', 'municipality_id' => 417],
            ['parish' => 'El Guayabo', 'municipality_id' => 418],
            ['parish' => 'Farriar', 'municipality_id' => 418],
            ['parish' => 'Isla de Toas', 'municipality_id' => 441],
            ['parish' => 'Monagas', 'municipality_id' => 441],
            ['parish' => 'San Timoteo', 'municipality_id' => 442],
            ['parish' => 'General Urdaneta', 'municipality_id' => 442],
            ['parish' => 'Libertador', 'municipality_id' => 442],
            ['parish' => 'Marcelino Briceño', 'municipality_id' => 442],
            ['parish' => 'Pueblo Nuevo', 'municipality_id' => 442],
            ['parish' => 'Manuel Guanipa Matos', 'municipality_id' => 442],
            ['parish' => 'Ambrosio', 'municipality_id' => 443],
            ['parish' => 'Carmen Herrera', 'municipality_id' => 443],
            ['parish' => 'La Rosa', 'municipality_id' => 443],
            ['parish' => 'Germán Ríos Linares', 'municipality_id' => 443],
            ['parish' => 'San Benito', 'municipality_id' => 443],
            ['parish' => 'Rómulo Betancourt', 'municipality_id' => 443],
            ['parish' => 'Jorge Hernández', 'municipality_id' => 443],
            ['parish' => 'Punta Gorda', 'municipality_id' => 443],
            ['parish' => 'Arístides Calvani', 'municipality_id' => 443],
            ['parish' => 'Encontrados', 'municipality_id' => 444],
            ['parish' => 'Udón Pérez', 'municipality_id' => 444],
            ['parish' => 'Moralito', 'municipality_id' => 445],
            ['parish' => 'San Carlos del Zulia', 'municipality_id' => 445],
            ['parish' => 'Santa Cruz del Zulia', 'municipality_id' => 445],
            ['parish' => 'Santa Bárbara', 'municipality_id' => 445],
            ['parish' => 'Urribarrí', 'municipality_id' => 445],
            ['parish' => 'Carlos Quevedo', 'municipality_id' => 446],
            ['parish' => 'Francisco Javier Pulgar', 'municipality_id' => 446],
            ['parish' => 'Simón Rodríguez', 'municipality_id' => 446],
            ['parish' => 'Guamo-Gavilanes', 'municipality_id' => 446],
            ['parish' => 'La Concepción', 'municipality_id' => 448],
            ['parish' => 'San José', 'municipality_id' => 448],
            ['parish' => 'Mariano Parra León', 'municipality_id' => 448],
            ['parish' => 'José Ramón Yépez', 'municipality_id' => 448],
            ['parish' => 'Jesús María Semprún', 'municipality_id' => 449],
            ['parish' => 'Barí', 'municipality_id' => 449],
            ['parish' => 'Concepción', 'municipality_id' => 450],
            ['parish' => 'Andrés Bello', 'municipality_id' => 450],
            ['parish' => 'Chiquinquirá', 'municipality_id' => 450],
            ['parish' => 'El Carmelo', 'municipality_id' => 450],
            ['parish' => 'Potreritos', 'municipality_id' => 450],
            ['parish' => 'Libertad', 'municipality_id' => 451],
            ['parish' => 'Alonso de Ojeda', 'municipality_id' => 451],
            ['parish' => 'Venezuela', 'municipality_id' => 451],
            ['parish' => 'Eleazar López Contreras', 'municipality_id' => 451],
            ['parish' => 'Campo Lara', 'municipality_id' => 451],
            ['parish' => 'Bartolomé de las Casas', 'municipality_id' => 452],
            ['parish' => 'Libertad', 'municipality_id' => 452],
            ['parish' => 'Río Negro', 'municipality_id' => 452],
            ['parish' => 'San José de Perijá', 'municipality_id' => 452],
            ['parish' => 'San Rafael', 'municipality_id' => 453],
            ['parish' => 'La Sierrita', 'municipality_id' => 453],
            ['parish' => 'Las Parcelas', 'municipality_id' => 453],
            ['parish' => 'Luis de Vicente', 'municipality_id' => 453],
            ['parish' => 'Monseñor Marcos Sergio Godoy', 'municipality_id' => 453],
            ['parish' => 'Ricaurte', 'municipality_id' => 453],
            ['parish' => 'Tamare', 'municipality_id' => 453],
            ['parish' => 'Antonio Borjas Romero', 'municipality_id' => 454],
            ['parish' => 'Bolívar', 'municipality_id' => 454],
            ['parish' => 'Cacique Mara', 'municipality_id' => 454],
            ['parish' => 'Carracciolo Parra Pérez', 'municipality_id' => 454],
            ['parish' => 'Cecilio Acosta', 'municipality_id' => 454],
            ['parish' => 'Cristo de Aranza', 'municipality_id' => 454],
            ['parish' => 'Coquivacoa', 'municipality_id' => 454],
            ['parish' => 'Chiquinquirá', 'municipality_id' => 454],
            ['parish' => 'Francisco Eugenio Bustamante', 'municipality_id' => 454],
            ['parish' => 'Idelfonzo Vásquez', 'municipality_id' => 454],
            ['parish' => 'Juana de Ávila', 'municipality_id' => 454],
            ['parish' => 'Luis Hurtado Higuera', 'municipality_id' => 454],
            ['parish' => 'Manuel Dagnino', 'municipality_id' => 454],
            ['parish' => 'Olegario Villalobos', 'municipality_id' => 454],
            ['parish' => 'Raúl Leoni', 'municipality_id' => 454],
            ['parish' => 'Santa Lucía', 'municipality_id' => 454],
            ['parish' => 'Venancio Pulgar', 'municipality_id' => 454],
            ['parish' => 'San Isidro', 'municipality_id' => 454],
            ['parish' => 'Altagracia', 'municipality_id' => 455],
            ['parish' => 'Faría', 'municipality_id' => 455],
            ['parish' => 'Ana María Campos', 'municipality_id' => 455],
            ['parish' => 'San Antonio', 'municipality_id' => 455],
            ['parish' => 'San José', 'municipality_id' => 455],
            ['parish' => 'Donaldo García', 'municipality_id' => 456],
            ['parish' => 'El Rosario', 'municipality_id' => 456],
            ['parish' => 'Sixto Zambrano', 'municipality_id' => 456],
            ['parish' => 'San Francisco', 'municipality_id' => 457],
            ['parish' => 'El Bajo', 'municipality_id' => 457],
            ['parish' => 'Domitila Flores', 'municipality_id' => 457],
            ['parish' => 'Francisco Ochoa', 'municipality_id' => 457],
            ['parish' => 'Los Cortijos', 'municipality_id' => 457],
            ['parish' => 'Marcial Hernández', 'municipality_id' => 457],
            ['parish' => 'Santa Rita', 'municipality_id' => 458],
            ['parish' => 'El Mene', 'municipality_id' => 458],
            ['parish' => 'Pedro Lucas Urribarrí', 'municipality_id' => 458],
            ['parish' => 'José Cenobio Urribarrí', 'municipality_id' => 458],
            ['parish' => 'Rafael Maria Baralt', 'municipality_id' => 459],
            ['parish' => 'Manuel Manrique', 'municipality_id' => 459],
            ['parish' => 'Rafael Urdaneta', 'municipality_id' => 459],
            ['parish' => 'Bobures', 'municipality_id' => 460],
            ['parish' => 'Gibraltar', 'municipality_id' => 460],
            ['parish' => 'Heras', 'municipality_id' => 460],
            ['parish' => 'Monseñor Arturo Álvarez', 'municipality_id' => 460],
            ['parish' => 'Rómulo Gallegos', 'municipality_id' => 460],
            ['parish' => 'El Batey', 'municipality_id' => 460],
            ['parish' => 'Rafael Urdaneta', 'municipality_id' => 461],
            ['parish' => 'La Victoria', 'municipality_id' => 461],
            ['parish' => 'Raúl Cuenca', 'municipality_id' => 461],
            ['parish' => 'Sinamaica', 'municipality_id' => 447],
            ['parish' => 'Alta Guajira', 'municipality_id' => 447],
            ['parish' => 'Elías Sánchez Rubio', 'municipality_id' => 447],
            ['parish' => 'Guajira', 'municipality_id' => 447],
            ['parish' => 'Altagracia', 'municipality_id' => 462],
            ['parish' => 'Antímano', 'municipality_id' => 462],
            ['parish' => 'Caricuao', 'municipality_id' => 462],
            ['parish' => 'Catedral', 'municipality_id' => 462],
            ['parish' => 'Coche', 'municipality_id' => 462],
            ['parish' => 'El Junquito', 'municipality_id' => 462],
            ['parish' => 'El Paraíso', 'municipality_id' => 462],
            ['parish' => 'El Recreo', 'municipality_id' => 462],
            ['parish' => 'El Valle', 'municipality_id' => 462],
            ['parish' => 'La Candelaria', 'municipality_id' => 462],
            ['parish' => 'La Pastora', 'municipality_id' => 462],
            ['parish' => 'La Vega', 'municipality_id' => 462],
            ['parish' => 'Macarao', 'municipality_id' => 462],
            ['parish' => 'San Agustín', 'municipality_id' => 462],
            ['parish' => 'San Bernardino', 'municipality_id' => 462],
            ['parish' => 'San José', 'municipality_id' => 462],
            ['parish' => 'San Juan', 'municipality_id' => 462],
            ['parish' => 'San Pedro', 'municipality_id' => 462],
            ['parish' => 'Santa Rosalía', 'municipality_id' => 462],
            ['parish' => 'Santa Teresa', 'municipality_id' => 462],
            ['parish' => 'Sucre (Catia)', 'municipality_id' => 462],
            ['parish' => '23 de enero', 'municipality_id' => 462],
        ]);
}
}
